### ISSUE TITLE
I am looking forward to this project!

### ISSUE THREAD

**Issue by imzoet** [CarlGao4/Demucs-Gui#2]
Hello, Is it near?

**Comment by 3vau** [comment]
Hello! Thanks for your support and we are encouraged by your expectation.

The UI part of the project have almost done, without a few test and enhancement. We decide to publish the first version before April, since we are just senior students so we couldn't put much time on it yet.

We will notice you when we're ready. It must worth your expectation🥳

**Comment by imzoet** [comment]
Thanks! Appreciate for your contribution!
